"""XumretService — the protocol API routes depend on.

Implemented by SingleMain (single mode) and ServerMain (server-executor mode,
deferred). Routes never know which implementation they hold.
"""

from __future__ import annotations

import asyncio
from typing import Protocol

from xumret.executor.models import PhoneCommand
from xumret.protocol.device import Device
from xumret.state.models import RunEvent, RunRecord


class XumretService(Protocol):
    async def list_devices(self) -> list[Device]: ...
    async def submit(self, phone_command: PhoneCommand) -> RunRecord: ...
    async def get(self, slug: str) -> RunRecord | None: ...
    async def list(self) -> list[RunRecord]: ...
    async def get_state(self, slug: str) -> RunRecord | None: ...
    async def stop(self, slug: str) -> RunRecord | None: ...
    async def reap(self, slug: str) -> bool: ...
    async def step_stdout_bytes(self, slug: str, step_index: int) -> bytes | None: ...
    def subscribe(self) -> asyncio.Queue[RunEvent]: ...
    def unsubscribe(self, queue: asyncio.Queue[RunEvent]) -> None: ...
