"""XumretService — the protocol that API routes depend on.

Implemented by SingleMain (single mode) and ServerMain (server-executor mode).
Routes never know which implementation they hold.
"""

from __future__ import annotations

import asyncio
from typing import Protocol

from xumret.executor.models import PhoneCommand
from xumret.server_bridge.models import DaemonEnded, DaemonStatusReport
from xumret.state.models import CommandHandle, CommandRecord, StateEvent


class XumretService(Protocol):
    async def submit(self, phone_command: PhoneCommand) -> CommandHandle: ...
    async def get(self, command_id: str) -> CommandRecord | None: ...
    async def list(self) -> list[CommandRecord]: ...
    async def cancel(self, command_id: str) -> CommandRecord | None: ...
    async def query_daemon(self, handle_id: str) -> DaemonStatusReport: ...
    async def end_daemon(self, handle_id: str) -> DaemonEnded: ...
    def subscribe(self) -> asyncio.Queue[StateEvent]: ...
    def unsubscribe(self, queue: asyncio.Queue[StateEvent]) -> None: ...
